### ISSUE TITLE
Doesn't seem to work anymore?

### ISSUE THREAD

**Issue by bluetidepro** [ericclemmons/grunt-verbosity#6]
I have:

	grunt.initConfig({
		verbosity: {
			options: { mode: 'hidden' },
			tasks: [
				'dog',
				'cat',
				'mouse',
				// etc.
			]
		},
	});

And it still seems to print everything, even with `hidden` on?

**Comment by ericclemmons** [comment]
TBH, I haven't worked on this or used a Grunt project in ~2 years so I have no idea what the landscape is like now :)

I'll accept PRs, but can't expend any effort otherwise.

**Comment by bluetidepro** [comment]
@ericclemmons Actually, it was my bad. I didn't realize you had to call the `verbosity` task also. I was just doing the config portion.
